redis:
  image: redis

postgres:
  image: postgres
  environment:
    POSTGRES_PASSWORD: secret
    POSTGRES_USER: sentry

sentry:
  image: sentry:8.3
  ports:
    - 8080:9000
  links:
    - redis
    - postgres
  environment:
    SENTRY_SECRET_KEY: ''

celerybeat:
  image: sentry:8.3
  links:
    - redis
    - postgres
  command: sentry celery beat
  environment:
    SENTRY_SECRET_KEY: ''

celeryworker:
  image: sentry:8.3
  links:
    - redis
    - postgres
  command: sentry celery worker
  environment:
    SENTRY_SECRET_KEY: ''
